code: mylogger
debug: false
testMode: false
pingInterval: 60
flushInterval: 10
queueFlushDelay: 100
maxBulkLog: 100
srcDb:
  host: localhost
  port: 3306
  user: zongji
  password: password
  database: util
dstDb:
  host: localhost
  port: 3306
  user: root
  password: password
  database: util
showFields:
  - name
  - description
castTypes:
  tinyint: boolean
logs:
  item:
    logTable: vn.itemLog
    mainTable: item
    tables:
      - name: item
        exclude:
          - image
          - supplyResponseFk
        types:
          isPrinted: boolean
      - name: itemTag
        relation: itemFk
