code: mylogger
debug: false
testMode: false
pingInterval: 300
flushInterval: 30
restartTimeout: 30
queueFlushDelay: 200
maxBulkLog: 100
upperCaseTable: true
serverId: 1
srcDb:
  host: localhost
  port: 3306
  user: zongji
  password: password
  database: util
dstDb:
  host: localhost
  port: 3306
  user: root
  password: password
  database: util
userField:
  - editorFk
showFields:
  - name
  - description
  - nickname
castTypes:
  tinyint: boolean
logs:
  item:
    logTable: itemLog
    mainTable: item
    tables:
      - name: item
        exclude:
          - image
          - supplyResponseFk
        types:
          isPrinted: boolean
      - name: itemTag
        relation: itemFk
