upperCaseTable: true
userField: editorFk
rowExcludeField: logExclude
excludeRegex: '__$'
showFields:
  - name
  - description
  - nickname
excludeFields:
  - created
  - updated
castTypes:
  tinyint: boolean
logs:
  item:
    logTable: itemLog
    mainTable: item
    tables:
      - itemTag
      - name: item
        showField: name
        exclude:
          - image
